use std::collections::HashMap;
use std::fs::File;
use std::io::{self, BufReader};
use std::sync::atomic::Ordering;

use crate::mining::{core::HuimAlgorithm, core::MiningContext, core::DataSource};
use crate::mining::components::{item_lists::ItemListBuilder, ul_join::{join_bodies, BodyAlloc, SpillArena, UlBody}};
use crate::mining::core::context::WriterProxy;
use crate::preprocessing::db_reader::DbReader;
use crate::types::{ItemId, ULEntry, Utility};
use smallvec::SmallVec;

/// Two-Phase, executed as a vertical (Eclat-style) DFS: candidates are generated by
/// TWU and their exact utility is accumulated from the same TID lists.
///
/// TID-list entries reuse `ULEntry`: `iutils` = utility of the itemset in the
/// transaction, `rutils` = the transaction's utility (its TWU contribution). Lists are
/// built by the budget-aware `ItemListBuilder`; derived lists are produced by streaming
/// joins and kept in RAM only while the budget allows (chunked and spilled otherwise).
pub struct TwoPhase;

impl TwoPhase {
    pub fn new() -> Self { Self }
}

impl HuimAlgorithm for TwoPhase {
    fn name(&self) -> &'static str { "Two-Phase (Vertical BufferPool)" }

    fn run(&mut self, source: DataSource, ctx: &mut MiningContext) -> io::Result<u64> {
        let file_path = source.expect_file("Two-Phase").to_path_buf();
        ctx.apply_os_safety_net();
        let min = ctx.min_utility;

        ctx.progress.set_stage("Phase 1: Computing 1-itemset TWUs");
        let mut twu_1: HashMap<ItemId, i64> = HashMap::new();
        for tx in DbReader::new(BufReader::new(File::open(&file_path)?)) {
            let tx = tx?;
            for e in &tx.items {
                *twu_1.entry(e.item).or_insert(0) += tx.transaction_utility;
            }
        }
        let mut valid: Vec<ItemId> = twu_1.iter().filter(|&(_, &t)| t >= min).map(|(&i, _)| i).collect();
        valid.sort_unstable();
        drop(twu_1);
        let valid_set: std::collections::HashSet<ItemId> = valid.iter().copied().collect();

        // Admission control: what cannot be spilled. Fixed: per-item list headers and the
        // builder's buffers (+ output queue). Per worker: one streaming join (3 input chunks + 1
        // output chunk), a spill-arena page and the list headers along the DFS path.
        {
            let n = valid.len().max(1);
            let multi = ctx.threads > 1;
            let estimate = |b: usize| -> (usize, usize) {
                let chunk_b = (b / 256 / 20).clamp(64, 4096) * 20;
                let queue = if multi { (b / 64).clamp(64 * 96, 100_000 * 96) } else { 0 };
                let fixed = n * (std::mem::size_of::<Ext>() + 96) + 2 * (b / 32).clamp(4 * 1024, 1 << 20) + queue;
                (fixed, 4 * chunk_b + (b / 64).clamp(4 * 1024, 256 * 1024) + 2 * n.min(4096) * std::mem::size_of::<Ext>())
            };
            ctx.admit("Two-Phase", &estimate)?;
        }

        ctx.progress.set_stage("Phase 2: Building Vertical Index (Inverted DB)");
        let alloc = BodyAlloc::new(&ctx.pool, &ctx.guard);
        let mut builder = ItemListBuilder::new(alloc, 0.5);
        for (tid, tx) in DbReader::new(BufReader::new(File::open(&file_path)?)).enumerate() {
            let tx = tx?;
            for e in &tx.items {
                if valid_set.contains(&e.item) {
                    builder.push(e.item, ULEntry { tid: tid as u32, iutils: e.utility, rutils: tx.transaction_utility })?;
                }
            }
        }
        drop(valid_set);
        let lists = builder.finish()?;
        crate::mining::core::memory_guard::release_free_memory();
        // `finish` returns lists sorted by item id. With rutils = transaction utility,
        // sum_iutils is the exact utility and sum_rutils the TWU.
        let top: Vec<Ext> = lists.into_iter()
            .map(|(i, ul, b)| Ext { item: i, exact: ul.sum_iutils, twu: ul.sum_rutils, body: b }).collect();
        let _hdr = ctx.guard.reserve_force(top.capacity() * std::mem::size_of::<Ext>());

        ctx.progress.set_stage("Phase 3: Vertical DFS (streaming TID-list joins)");
        let top_ref = &top;
        ctx.execute_tasks((0..top.len()).collect::<Vec<usize>>(), |i, proxy| {
            let arena = SpillArena::new(&ctx.pool, &ctx.guard);
            let alloc = BodyAlloc::new(&ctx.pool, &ctx.guard).with_arena(&arena);
            let mut prefix = Vec::new();
            if let Err(e) = visit(&mut prefix, None, top_ref, i, alloc, ctx, proxy) {
                eprintln!("Two-Phase task failed: {}", e);
            }
        });

        ctx.progress.set_stage("Mining Complete");
        Ok(ctx.progress.huis_found.load(Ordering::Relaxed))
    }
}

/// A candidate P·x: its TID list (entries: tid, utility of P·x in the transaction, transaction
/// utility), exact utility and TWU.
struct Ext {
    item: ItemId,
    exact: Utility,
    twu: Utility,
    body: UlBody,
}

/// Visit candidate `sibs[i]` (= P·x, where `prefix_body` is P's list): output it if it is a HUI,
/// then extend it by every later sibling P·y whose join P·x·y keeps TWU >= min. Each join is a
/// streaming merge of three lists (P, P·x, P·y): list(P·x·y) has utility
/// u(P·x) + u(P·y) - u(P) per shared transaction. Lists are chunked and spilled as the budget
/// requires, so a join's working set is a few chunks whatever the list lengths.
fn visit(
    prefix: &mut Vec<ItemId>,
    prefix_body: Option<&UlBody>,
    sibs: &[Ext],
    i: usize,
    alloc: BodyAlloc,
    ctx: &MiningContext,
    proxy: &mut WriterProxy,
) -> io::Result<()> {
    let min = ctx.min_utility;
    let x = &sibs[i];
    prefix.push(x.item);
    ctx.progress.current_depth.store(prefix.len(), Ordering::Relaxed);
    if x.exact >= min {
        proxy.write_hui(prefix, x.exact)?;
        ctx.progress.huis_found.fetch_add(1, Ordering::Relaxed);
    }
    let mut next: Vec<Ext> = Vec::new();
    for y in &sibs[i + 1..] {
        let joined = join_bodies(SmallVec::new(), prefix_body, &x.body, &y.body, alloc, None)?;
        if let Some((ul, body)) = joined {
            ctx.progress.fast_path_reads.fetch_add(ul.len as u64, Ordering::Relaxed);
            if ul.len > 0 && ul.sum_rutils >= min {
                next.push(Ext { item: y.item, exact: ul.sum_iutils, twu: ul.sum_rutils, body });
            }
        }
    }
    let _hdr = ctx.guard.reserve_force(next.capacity() * std::mem::size_of::<Ext>());
    for j in 0..next.len() {
        visit(prefix, Some(&x.body), &next, j, alloc, ctx, proxy)?;
        // This branch is finished: release its list now rather than at the end of the level.
        next[j].body = UlBody::InMemory(Vec::new(), None);
    }
    prefix.pop();
    Ok(())
}
