use std::collections::HashMap;
use std::fs::File;
use std::io::{self, BufReader};
use std::sync::atomic::Ordering;

use crate::mining::{core::HuimAlgorithm, core::MiningContext, core::DataSource};
use crate::mining::components::{item_lists::ItemListBuilder, ul_join::{BodyAlloc, SpillArena, UlBody}};
use crate::mining::core::context::WriterProxy;
use crate::preprocessing::db_reader::DbReader;
use crate::types::{ItemId, ULEntry, Utility};

/// Two-Phase, executed as a vertical (Eclat-style) DFS: candidates are generated by
/// TWU and their exact utility is accumulated from the same TID lists.
///
/// TID-list entries reuse `ULEntry`: `iutils` = utility of the itemset in the
/// transaction, `rutils` = the transaction's TWU contribution (its utility). Lists are
/// built by the budget-aware `ItemListBuilder` and every derived list is kept in RAM
/// only while the budget allows (spilled otherwise).
pub struct TwoPhase;

impl TwoPhase {
    pub fn new() -> Self { Self }
}

impl HuimAlgorithm for TwoPhase {
    fn name(&self) -> &'static str { "Two-Phase (Vertical BufferPool)" }

    fn run(&mut self, source: DataSource, ctx: &mut MiningContext) -> io::Result<u64> {
        let file_path = source.expect_file("Two-Phase").to_path_buf();
        ctx.apply_os_safety_net();
        let min = ctx.min_utility;

        ctx.progress.set_stage("Phase 1: Computing 1-itemset TWUs");
        let mut twu_1: HashMap<ItemId, i64> = HashMap::new();
        for tx in DbReader::new(BufReader::new(File::open(&file_path)?)) {
            let tx = tx?;
            for e in &tx.items {
                *twu_1.entry(e.item).or_insert(0) += tx.transaction_utility;
            }
        }
        let mut valid: Vec<ItemId> = twu_1.iter().filter(|&(_, &t)| t >= min).map(|(&i, _)| i).collect();
        valid.sort_unstable();
        drop(twu_1);
        let valid_set: std::collections::HashSet<ItemId> = valid.iter().copied().collect();

        ctx.progress.set_stage("Phase 2: Building Vertical Index (Inverted DB)");
        let alloc = BodyAlloc::new(&ctx.pool, &ctx.guard);
        let mut builder = ItemListBuilder::new(alloc, 0.5);
        for (tid, tx) in DbReader::new(BufReader::new(File::open(&file_path)?)).enumerate() {
            let tx = tx?;
            for e in &tx.items {
                if valid_set.contains(&e.item) {
                    builder.push(e.item, ULEntry { tid: tid as u32, iutils: e.utility, rutils: tx.transaction_utility })?;
                }
            }
        }
        drop(valid_set);
        let lists = builder.finish()?;
        crate::mining::core::memory_guard::release_free_memory();
        // `finish` returns lists sorted by item id, matching `valid`.
        let bodies: Vec<(ItemId, UlBody)> = lists.into_iter().map(|(i, _, b)| (i, b)).collect();

        ctx.progress.set_stage("Phase 3: Vertical DFS Execution (BufferPool-backed)");
        let bodies_ref = &bodies;
        ctx.execute_tasks((0..bodies.len()).collect::<Vec<usize>>(), |i, proxy| {
            let arena = SpillArena::new(&ctx.pool, &ctx.guard);
            let alloc = BodyAlloc::new(&ctx.pool, &ctx.guard).with_arena(&arena);
            let mut prefix = vec![bodies_ref[i].0];
            let run = |proxy: &mut WriterProxy, prefix: &mut Vec<ItemId>| -> io::Result<()> {
                let tids = alloc.view(&bodies_ref[i].1)?;
                let exact: Utility = tids.iter().map(|e| e.iutils).sum();
                if exact >= min {
                    proxy.write_hui(prefix, exact)?;
                    ctx.progress.huis_found.fetch_add(1, Ordering::Relaxed);
                }
                let exts: Vec<usize> = (i + 1..bodies_ref.len()).collect();
                dfs(prefix, &exts, &tids, bodies_ref, alloc, ctx, proxy)
            };
            if let Err(e) = run(proxy, &mut prefix) {
                eprintln!("Two-Phase task failed: {}", e);
            }
        });

        ctx.progress.set_stage("Mining Complete");
        Ok(ctx.progress.huis_found.load(Ordering::Relaxed))
    }
}

/// Recursive vertical DFS using TID-list intersection (Eclat style).
fn dfs(
    prefix: &mut Vec<ItemId>,
    extensions: &[usize],
    tids: &[ULEntry],
    items: &[(ItemId, UlBody)],
    alloc: BodyAlloc,
    ctx: &MiningContext,
    proxy: &mut WriterProxy,
) -> io::Result<()> {
    let min = ctx.min_utility;
    ctx.progress.current_depth.store(prefix.len() + 1, Ordering::Relaxed);

    let mut valid_exts: Vec<usize> = Vec::new();
    let mut next_lists: Vec<UlBody> = Vec::new();

    for &ext_idx in extensions {
        let ext_list = alloc.view(&items[ext_idx].1)?;
        let _scratch = ctx.guard.reserve_force(tids.len().min(ext_list.len()) * 20);
        let mut next: Vec<ULEntry> = Vec::with_capacity(tids.len().min(ext_list.len()));
        let mut twu = 0;
        let mut exact = 0;
        let (mut i, mut j) = (0, 0);
        while i < tids.len() && j < ext_list.len() {
            let (p, x) = (tids[i], ext_list[j]);
            let (pt, xt) = (p.tid, x.tid);
            if pt == xt {
                let u = p.iutils + x.iutils;
                next.push(ULEntry { tid: pt, iutils: u, rutils: p.rutils });
                twu += p.rutils;
                exact += u;
                i += 1;
                j += 1;
            } else if pt < xt {
                i += 1;
            } else {
                j += 1;
            }
        }
        ctx.progress.fast_path_reads.fetch_add((i + j) as u64, Ordering::Relaxed);

        if !next.is_empty() && exact >= min {
            prefix.push(items[ext_idx].0);
            proxy.write_hui(prefix, exact)?;
            ctx.progress.huis_found.fetch_add(1, Ordering::Relaxed);
            prefix.pop();
        }
        if !next.is_empty() && twu >= min {
            valid_exts.push(ext_idx);
            drop(_scratch);
            next_lists.push(alloc.make_body(next)?);
        }
    }

    let _hdr = ctx.guard.reserve_force(next_lists.capacity() * std::mem::size_of::<UlBody>());
    for idx in 0..valid_exts.len() {
        prefix.push(items[valid_exts[idx]].0);
        {
            let next_tids = alloc.view(&next_lists[idx])?;
            dfs(prefix, &valid_exts[idx + 1..], &next_tids, items, alloc, ctx, proxy)?;
        }
        // This branch is finished: release its list now rather than at the end of the level.
        next_lists[idx] = UlBody::InMemory(Vec::new(), None);
        prefix.pop();
    }
    Ok(())
}
